endpoints:
  - name: default
    port: 8080
    ingress:
      domain: hosp.dev.loyaltypoint.io
      environment: prod
      class: qa
      letsencrypt: true

deploy:
  k8sNamespace: misc
  k8sUser: gitlab
